name       : python-ipyparallel
version    : 8.1.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/i/ipyparallel/ipyparallel-8.1.0.tar.gz : 63f7e136e88f890e9802522fa5475dd81e7614ba06a8cfe4f80cc3056fdb7d73
homepage   : https://ipython.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Interactive Parallel Computing with IPython
description: |
    IPython Parallel (ipyparallel) is a Python package and collection of CLI scripts for controlling clusters of IPython processes, built on the Jupyter protocol.
builddeps  :
    - python-packaging
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-psutil
    - python-pyzmq
    - python-tqdm
    - python-traitlets
    - python3-ipython
build      : |
    %python3_setup
install    : |
    %python3_install
