name       : python-ipyparallel
version    : 8.2.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/i/ipyparallel/ipyparallel-8.2.1.tar.gz : f267473c52fc6a886c6b816adb155bec0b277bc7d224fb3fabeb83834e733c72
homepage   : https://ipython.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Interactive Parallel Computing with IPython
description: |
    IPython Parallel (ipyparallel) is a Python package and collection of CLI scripts for controlling clusters of IPython processes, built on the Jupyter protocol.
builddeps  :
    - python-packaging
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-psutil
    - python-pyzmq
    - python-tqdm
    - python-traitlets
    - python3-ipython
build      : |
    %python3_setup
install    : |
    %python3_install
